name: jax
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- absl-py=2.0.0
- alsa-lib=1.2.10
- attr=2.5.1
- brotli=1.1.0
- brotli-bin=1.1.0
- bzip2=1.0.8
- c-ares=1.24.0
- ca-certificates=2023.11.17
- cairo=1.18.0
- certifi=2023.11.17
- contourpy=1.2.0
- cycler=0.12.1
- dbus=1.13.6
- expat=2.5.0
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.47.0
- freetype=2.12.1
- gettext=0.21.1
- glib=2.78.3
- glib-tools=2.78.3
- graphite2=1.3.13
- gst-plugins-base=1.22.7
- gstreamer=1.22.7
- harfbuzz=8.3.0
- icu=73.2
- importlib-metadata=7.0.0
- importlib_metadata=7.0.0
- keyutils=1.6.1
- kiwisolver=1.4.5
- krb5=1.21.2
- lame=3.100
- lcms2=2.16
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libabseil=20230802.1
- libblas=3.9.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcap=2.69
- libcblas=3.9.0
- libclang=15.0.7
- libclang13=15.0.7
- libcups=2.3.3
- libdeflate=1.19
- libedit=3.1.20191231
- libevent=2.1.12
- libexpat=2.5.0
- libffi=3.4.2
- libflac=1.4.3
- libgcc-ng=13.2.0
- libgcrypt=1.10.3
- libgfortran-ng=13.2.0
- libgfortran5=13.2.0
- libglib=2.78.3
- libgomp=13.2.0
- libgpg-error=1.47
- libgrpc=1.58.2
- libiconv=1.17
- libjpeg-turbo=3.0.0
- liblapack=3.9.0
- libllvm15=15.0.7
- libnsl=2.0.1
- libogg=1.3.4
- libopenblas=0.3.25
- libopus=1.3.1
- libpng=1.6.39
- libpq=16.1
- libprotobuf=4.24.3
- libre2-11=2023.06.02
- libsndfile=1.2.2
- libsqlite=3.44.2
- libstdcxx-ng=13.2.0
- libsystemd0=255
- libtiff=4.6.0
- libuuid=2.38.1
- libvorbis=1.3.7
- libwebp-base=1.3.2
- libxcb=1.15
- libxkbcommon=1.6.0
- libxml2=2.12.3
- libzlib=1.2.13
- lz4-c=1.9.4
- matplotlib=3.8.2
- matplotlib-base=3.8.2
- ml_dtypes=0.3.1
- mpg123=1.32.3
- munkres=1.1.4
- mysql-common=8.0.33
- mysql-libs=8.0.33
- ncurses=6.4
- networkx=3.2.1
- nspr=4.35
- nss=3.96
- openjpeg=2.5.0
- openssl=3.2.0
- opt-einsum=3.3.0
- opt_einsum=3.3.0
- packaging=23.2
- pcre2=10.42
- pillow=10.1.0
- pip=23.3.2
- pixman=0.42.2
- ply=3.11
- pthread-stubs=0.4
- pulseaudio-client=16.1
- pyparsing=3.1.1
- pyqt=5.15.9
- pyqt5-sip=12.12.2
- python=3.11.7
- python-dateutil=2.8.2
- python_abi=3.11
- qt-main=5.15.8
- re2=2023.06.02
- readline=8.2
- scipy=1.11.4
- setuptools=68.2.2
- sip=6.7.12
- six=1.16.0
- tk=8.6.13
- toml=0.10.2
- tomli=2.0.1
- tornado=6.3.3
- tzdata=2023c
- wheel=0.42.0
- xcb-util=0.4.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.0
- xcb-util-renderutil=0.3.9
- xcb-util-wm=0.4.1
- xkeyboard-config=2.40
- xorg-kbproto=1.0.7
- xorg-libice=1.1.1
- xorg-libsm=1.2.4
- xorg-libx11=1.8.7
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.11
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xf86vidmodeproto=2.3.1
- xorg-xproto=7.0.31
- xz=5.2.6
- zipp=3.17.0
- zlib=1.2.13
- zstd=1.5.5

