!!python/object:ml_collections.config_dict.config_dict.ConfigDict
_convert_dict: true
_fields:
  experiment: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      batch_size: 100
      chain_length: 100000
      ess_ratio: 0.5
      evaluator: ess_eval
      fig_folder: /gcs/xcloud-shared/kgoshvadi/results/discs/discs-categorical-sampler_sweep_56324581/14_sampler_config.name='path_auxiliary',model_config.init_sigma=1.5,model_config.num_categories=8,sampler_config.balancing_fn_type='RATIO'/logs/figures
      get_additional_metrics: false
      log_every_steps: 100
      name: Sampling_Experiment
      num_models: 1
      plot_every_steps: 10
      run_parallel: false
      save_every_steps: 10000
      save_root: /gcs/xcloud-shared/kgoshvadi/results/discs/discs-categorical-sampler_sweep_56324581/14_sampler_config.name='path_auxiliary',model_config.init_sigma=1.5,model_config.num_categories=8,sampler_config.balancing_fn_type='RATIO'
      shuffle_buffer_size: 0
      use_tqdm: false
    _locked: false
    _type_safe: true
  model: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      data_root: sco
      init_sigma: 1.5
      name: categorical
      num_categories: 8
      save_dir_name: categorical_4
      shape: !!python/tuple
      - 2000
    _locked: false
    _type_safe: true
  sampler: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      adaptive: true
      balancing_fn_type: RATIO
      name: path_auxiliary
      num_flips: 1
      target_acceptance_rate: 0.574
      use_fast_path: true
    _locked: false
    _type_safe: true
_locked: false
_type_safe: true
